// Generated by https://quicktype.io

export interface LoginData {
  correo: string;
  password: string;
}

export interface RegisterData {
  nombre: string;
  correo: string;
  password: string;
}

export interface LoginResponse {
  usuario: Usuario;
  token: string;
}

export interface Usuario {
  nombre: string;
  correo: string;
  rol: string;
  estado: boolean;
  google: boolean;
  uid: string;
  img?: string;
}

// Generated by https://quicktype.io

export interface ProductsResponse {
  total: number;
  productos: Product[];
}

export interface Product {
  _id: string;
  nombre: string;
  usuario: Categoria;
  precio: number;
  categoria: Categoria;
  img?: string;
}

export interface CategoriesResponse {
  total: number;
  categorias: Categoria[];
}

export interface Categoria {
  _id: string;
  nombre: string;
  usuario?: CreatedBy;
}

export interface CreatedBy {
  _id: string;
  nombre: string;
}

export enum ID {
  The63Aad20C62872289103D41F4 = '63aad20c62872289103d41f4',
  The63Aad39862872289103D41Fa = '63aad39862872289103d41fa',
}

export enum Nombre {
  Controls = 'CONTROLS',
  Test1 = 'test 1',
}
